amf:
  amf_name: open5gs-amf0
  guami:
  - amf_id:
      region: 2
      set: 1
    plmn_id:
      mcc: '001'
      mnc: '01'
  network_name:
    full: Open5GS
  ngap:
  - addr: 192.168.0.111
  plmn_support:
  - plmn_id:
      mcc: '001'
      mnc: '01'
    s_nssai:
    - sd: 1
      sst: 1
    - sd: 1
      sst: 2
    - sd: 1
      sst: 3
    - sd: 1
      sst: 4
  sbi:
  - addr: 127.0.0.5
    port: 7777
  security:
    ciphering_order:
    - NEA0
    - NEA1
    - NEA2
    integrity_order:
    - NIA2
    - NIA1
    - NIA0
  tai:
  - plmn_id:
      mcc: '001'
      mnc: '01'
    tac: 1
logger:
  file: /open5gs/install/var/log/open5gs/amf.log
max: null
nrf:
  sbi:
  - addr:
    - 127.0.0.10
    port: 7777
parameter: null
pool: null
sctp: null
sockopt: null
time: null
