logger:
  file: /open5gs/install/var/log/open5gs/upf_default.log
max: null
parameter: null
pool: null
smf: null
time: null
upf:
  gtpu:
  - addr: 192.168.0.112
  pfcp:
  - addr: 192.168.0.112
  subnet:
  - addr: 192.168.2.1/24
    dev: ogstun
    dnn: default
