logger:
  file: /open5gs/install/var/log/open5gs/upf_internet.log
max: null
parameter: null
pool: null
smf: null
time: null
upf:
  gtpu:
  - addr: 192.168.0.113
  pfcp:
  - addr: 192.168.0.113
  subnet:
  - addr: 192.168.3.1/24
    dev: ogstun
    dnn: internet
