logger:
  file: /open5gs/install/var/log/open5gs/upf_internert.log
max: null
parameter: null
pool: null
smf: null
time: null
upf:
  gtpu:
  - addr: 192.168.0.113
  pfcp:
  - addr: 192.168.0.113
  subnet:
  - addr: 10.46.0.1/16
    dev: ogstun
    dnn: internert
