amf: '8000'
ciphering:
  EA1: true
  EA2: true
  EA3: true
configured-nssai:
- sd: 1
  sst: 1
default-nssai:
- sd: 1
  sst: 1
gnbSearchList:
- 192.168.0.131
imei: '356938035643803'
imeiSv: '4370816125816151'
integrity:
  IA1: true
  IA2: true
  IA3: true
integrityMaxRate:
  downlink: full
  uplink: full
key: 8baf473f2f8fd09487cccbd7097c6862
mcc: '001'
mnc: '01'
op: '11111111111111111111111111111111'
opType: OP
sessions:
- emergency: false
  slice:
    sd: 1
    sst: 1
  type: IPv4
supi: imsi-001011234567895
uacAcc:
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
  normalClass: 0
uacAic:
  mcs: false
  mps: false
